// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.25.0
// source: deviceinfo/deviceInfo.proto

package deviceinfo

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContainerDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParetDeviceId string                 `protobuf:"bytes,1,opt,name=paret_device_id,json=paretDeviceId,proto3" json:"paret_device_id,omitempty"`
	MigDeviceId   string                 `protobuf:"bytes,2,opt,name=mig_device_id,json=migDeviceId,proto3" json:"mig_device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerDevice) Reset() {
	*x = ContainerDevice{}
	mi := &file_deviceinfo_deviceInfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerDevice) ProtoMessage() {}

func (x *ContainerDevice) ProtoReflect() protoreflect.Message {
	mi := &file_deviceinfo_deviceInfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerDevice.ProtoReflect.Descriptor instead.
func (*ContainerDevice) Descriptor() ([]byte, []int) {
	return file_deviceinfo_deviceInfo_proto_rawDescGZIP(), []int{0}
}

func (x *ContainerDevice) GetParetDeviceId() string {
	if x != nil {
		return x.ParetDeviceId
	}
	return ""
}

func (x *ContainerDevice) GetMigDeviceId() string {
	if x != nil {
		return x.MigDeviceId
	}
	return ""
}

type ContainerDevices struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ContainerName    string                 `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	ContainerDevices []*ContainerDevice     `protobuf:"bytes,2,rep,name=container_devices,json=containerDevices,proto3" json:"container_devices,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ContainerDevices) Reset() {
	*x = ContainerDevices{}
	mi := &file_deviceinfo_deviceInfo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerDevices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerDevices) ProtoMessage() {}

func (x *ContainerDevices) ProtoReflect() protoreflect.Message {
	mi := &file_deviceinfo_deviceInfo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerDevices.ProtoReflect.Descriptor instead.
func (*ContainerDevices) Descriptor() ([]byte, []int) {
	return file_deviceinfo_deviceInfo_proto_rawDescGZIP(), []int{1}
}

func (x *ContainerDevices) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *ContainerDevices) GetContainerDevices() []*ContainerDevice {
	if x != nil {
		return x.ContainerDevices
	}
	return nil
}

type PodDeviceInfo struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	PodName          string                       `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	ContainerDevices map[string]*ContainerDevices `protobuf:"bytes,2,rep,name=container_devices,json=containerDevices,proto3" json:"container_devices,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PodDeviceInfo) Reset() {
	*x = PodDeviceInfo{}
	mi := &file_deviceinfo_deviceInfo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodDeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodDeviceInfo) ProtoMessage() {}

func (x *PodDeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_deviceinfo_deviceInfo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodDeviceInfo.ProtoReflect.Descriptor instead.
func (*PodDeviceInfo) Descriptor() ([]byte, []int) {
	return file_deviceinfo_deviceInfo_proto_rawDescGZIP(), []int{2}
}

func (x *PodDeviceInfo) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *PodDeviceInfo) GetContainerDevices() map[string]*ContainerDevices {
	if x != nil {
		return x.ContainerDevices
	}
	return nil
}

type PodDeviceInfos struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	PodDeviceinfos map[string]*PodDeviceInfo `protobuf:"bytes,1,rep,name=pod_deviceinfos,json=podDeviceinfos,proto3" json:"pod_deviceinfos,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PodDeviceInfos) Reset() {
	*x = PodDeviceInfos{}
	mi := &file_deviceinfo_deviceInfo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodDeviceInfos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodDeviceInfos) ProtoMessage() {}

func (x *PodDeviceInfos) ProtoReflect() protoreflect.Message {
	mi := &file_deviceinfo_deviceInfo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodDeviceInfos.ProtoReflect.Descriptor instead.
func (*PodDeviceInfos) Descriptor() ([]byte, []int) {
	return file_deviceinfo_deviceInfo_proto_rawDescGZIP(), []int{3}
}

func (x *PodDeviceInfos) GetPodDeviceinfos() map[string]*PodDeviceInfo {
	if x != nil {
		return x.PodDeviceinfos
	}
	return nil
}

var File_deviceinfo_deviceInfo_proto protoreflect.FileDescriptor

const file_deviceinfo_deviceInfo_proto_rawDesc = "" +
	"\n" +
	"\x1bdeviceinfo/deviceInfo.proto\x12\n" +
	"deviceinfo\x1a\x1bgoogle/protobuf/empty.proto\"]\n" +
	"\x0fContainerDevice\x12&\n" +
	"\x0fparet_device_id\x18\x01 \x01(\tR\rparetDeviceId\x12\"\n" +
	"\rmig_device_id\x18\x02 \x01(\tR\vmigDeviceId\"\x83\x01\n" +
	"\x10ContainerDevices\x12%\n" +
	"\x0econtainer_name\x18\x01 \x01(\tR\rcontainerName\x12H\n" +
	"\x11container_devices\x18\x02 \x03(\v2\x1b.deviceinfo.ContainerDeviceR\x10containerDevices\"\xeb\x01\n" +
	"\rPodDeviceInfo\x12\x19\n" +
	"\bpod_name\x18\x01 \x01(\tR\apodName\x12\\\n" +
	"\x11container_devices\x18\x02 \x03(\v2/.deviceinfo.PodDeviceInfo.ContainerDevicesEntryR\x10containerDevices\x1aa\n" +
	"\x15ContainerDevicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.deviceinfo.ContainerDevicesR\x05value:\x028\x01\"\xc7\x01\n" +
	"\x0ePodDeviceInfos\x12W\n" +
	"\x0fpod_deviceinfos\x18\x01 \x03(\v2..deviceinfo.PodDeviceInfos.PodDeviceinfosEntryR\x0epodDeviceinfos\x1a\\\n" +
	"\x13PodDeviceinfosEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.deviceinfo.PodDeviceInfoR\x05value:\x028\x012\xaa\x01\n" +
	"\n" +
	"DeviceInfo\x12M\n" +
	"\x15listAllMigDeviceInfos\x12\x16.google.protobuf.Empty\x1a\x1a.deviceinfo.PodDeviceInfos\"\x00\x12M\n" +
	"\x13watchMigDeviceInfos\x12\x16.google.protobuf.Empty\x1a\x1a.deviceinfo.PodDeviceInfos\"\x000\x01B'Z%github.com/ckLearning/grpc/deviceinfob\x06proto3"

var (
	file_deviceinfo_deviceInfo_proto_rawDescOnce sync.Once
	file_deviceinfo_deviceInfo_proto_rawDescData []byte
)

func file_deviceinfo_deviceInfo_proto_rawDescGZIP() []byte {
	file_deviceinfo_deviceInfo_proto_rawDescOnce.Do(func() {
		file_deviceinfo_deviceInfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deviceinfo_deviceInfo_proto_rawDesc), len(file_deviceinfo_deviceInfo_proto_rawDesc)))
	})
	return file_deviceinfo_deviceInfo_proto_rawDescData
}

var file_deviceinfo_deviceInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_deviceinfo_deviceInfo_proto_goTypes = []any{
	(*ContainerDevice)(nil),  // 0: deviceinfo.ContainerDevice
	(*ContainerDevices)(nil), // 1: deviceinfo.ContainerDevices
	(*PodDeviceInfo)(nil),    // 2: deviceinfo.PodDeviceInfo
	(*PodDeviceInfos)(nil),   // 3: deviceinfo.PodDeviceInfos
	nil,                      // 4: deviceinfo.PodDeviceInfo.ContainerDevicesEntry
	nil,                      // 5: deviceinfo.PodDeviceInfos.PodDeviceinfosEntry
	(*empty.Empty)(nil),      // 6: google.protobuf.Empty
}
var file_deviceinfo_deviceInfo_proto_depIdxs = []int32{
	0, // 0: deviceinfo.ContainerDevices.container_devices:type_name -> deviceinfo.ContainerDevice
	4, // 1: deviceinfo.PodDeviceInfo.container_devices:type_name -> deviceinfo.PodDeviceInfo.ContainerDevicesEntry
	5, // 2: deviceinfo.PodDeviceInfos.pod_deviceinfos:type_name -> deviceinfo.PodDeviceInfos.PodDeviceinfosEntry
	1, // 3: deviceinfo.PodDeviceInfo.ContainerDevicesEntry.value:type_name -> deviceinfo.ContainerDevices
	2, // 4: deviceinfo.PodDeviceInfos.PodDeviceinfosEntry.value:type_name -> deviceinfo.PodDeviceInfo
	6, // 5: deviceinfo.DeviceInfo.listAllMigDeviceInfos:input_type -> google.protobuf.Empty
	6, // 6: deviceinfo.DeviceInfo.watchMigDeviceInfos:input_type -> google.protobuf.Empty
	3, // 7: deviceinfo.DeviceInfo.listAllMigDeviceInfos:output_type -> deviceinfo.PodDeviceInfos
	3, // 8: deviceinfo.DeviceInfo.watchMigDeviceInfos:output_type -> deviceinfo.PodDeviceInfos
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_deviceinfo_deviceInfo_proto_init() }
func file_deviceinfo_deviceInfo_proto_init() {
	if File_deviceinfo_deviceInfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deviceinfo_deviceInfo_proto_rawDesc), len(file_deviceinfo_deviceInfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deviceinfo_deviceInfo_proto_goTypes,
		DependencyIndexes: file_deviceinfo_deviceInfo_proto_depIdxs,
		MessageInfos:      file_deviceinfo_deviceInfo_proto_msgTypes,
	}.Build()
	File_deviceinfo_deviceInfo_proto = out.File
	file_deviceinfo_deviceInfo_proto_goTypes = nil
	file_deviceinfo_deviceInfo_proto_depIdxs = nil
}
